server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application.name: test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  activemq:
    broker-url: "tcp://localhost:61616"

springdoc:
  packages-to-scan: "ru.mts"
  swagger-ui:
    path: "/swagger"
    showCommonExtensions: true
    defaultModelsExpandDepth: -1

logging:
  config: "logback.xml"

debug: true