version: '3.3'
services:
  activemq:
    #    restart: always
    image: vromero/activemq-artemis
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ARTEMIS_USERNAME: root
      ARTEMIS_PASSWORD: test
  test_mts:
    #    restart: always
    image: nikitij351/test-mts:latest
    depends_on:
      - activemq
    ports:
      - "8091:8080"
    working_dir: /opt/test_mts
    volumes:
      - ./logs:/opt/test_mts/log
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    environment:
      - SPRING_ACTIVEMQ_USER=root
      - SPRING_ACTIVEMQ_PASSWORD=test
      - LOGGING_FILE_PATH=log