version: '3.3'
services:
  activemq:
    #    restart: always
    image: vromero/activemq-artemis
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ARTEMIS_USERNAME: myuser
      ARTEMIS_PASSWORD: otherpassword
  test_mts:
    #    restart: always
    image: nikitij351/test-mts:latest
    depends_on:
      - activemq
    ports:
      - "8090:8080"